[workspace]
members = ["whirl_tf", "whirl_tf_py"]
resolver = "2"

[workspace.package]
version = "0.1.0-alpha.1"
edition = "2024"
authors = ["Team whIRLwind"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/IntelligentRoboticsLab/whirl_tf"
readme = "README.md"

[workspace.lints.clippy]
all = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
inline_always = "allow"
missing_errors_doc = "allow"
missing_panics_doc = "allow"
type_complexity = "allow"

[workspace.dependencies]
whirl_tf = { path = "whirl_tf", version = "0.1.0-alpha.1", default-features = false }

nalgebra = "0.34"
pyo3 = { version = "0.29", default-features = false, features = [
    "macros",
    "abi3-py311",
] }
pyo3-stub-gen = { version = "0.23", default-features = false }
thiserror = "2.0.18"
transforms = { version = "=2.0.0-beta.4", default-features = false, features = [
    "std",
] }
