# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import typing

__all__ = [
    "ALL",
    "BASE_FOOTPRINT",
    "BASE_LINK",
    "FIELD",
    "FrameError",
    "GAZE",
    "LEFT_CAMERA_LINK",
    "LEFT_CAMERA_OPTICAL_FRAME",
    "LEFT_SOLE",
    "ODOM",
    "RIGHT_SOLE",
    "TORSO",
    "TransformBuffer",
    "TransformError",
    "require_frame",
]

ALL: builtins.list[builtins.str]
BASE_FOOTPRINT: builtins.str
BASE_LINK: builtins.str
FIELD: builtins.str
GAZE: builtins.str
LEFT_CAMERA_LINK: builtins.str
LEFT_CAMERA_OPTICAL_FRAME: builtins.str
LEFT_SOLE: builtins.str
ODOM: builtins.str
RIGHT_SOLE: builtins.str
TORSO: builtins.str

class FrameError(builtins.Exception): ...

@typing.final
class TransformBuffer:
    def __new__(cls, history_seconds: builtins.float) -> TransformBuffer: ...
    def insert_transform(
        self,
        parent: builtins.str,
        child: builtins.str,
        matrix: typing.Sequence[typing.Sequence[builtins.float]],
        stamp_ns: builtins.int,
        is_static: builtins.bool = ...,
    ) -> None: ...
    def insert_transform_stamped(
        self, message: typing.Any, is_static: builtins.bool = ...
    ) -> None: ...
    def insert_transform_message(
        self, message: typing.Any, is_static: builtins.bool = ...
    ) -> None: ...
    def lookup(
        self, from_frame: builtins.str, to_frame: builtins.str, stamp_ns: builtins.int
    ) -> builtins.list[builtins.list[builtins.float]]: ...
    def can_transform(
        self, from_frame: builtins.str, to_frame: builtins.str, stamp_ns: builtins.int
    ) -> builtins.bool: ...
    def clear_dynamic(self) -> None: ...

class TransformError(builtins.Exception): ...

def require_frame(
    actual: builtins.str, expected: builtins.str, interface: builtins.str
) -> None: ...
