# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import typing

__all__ = [
    "ALL",
    "BASE_FOOTPRINT",
    "BASE_LINK",
    "FIELD",
    "FilterFailureReason",
    "FrameError",
    "GAZE",
    "LEFT_CAMERA_LINK",
    "LEFT_CAMERA_OPTICAL_FRAME",
    "LEFT_SOLE",
    "MessageFilter",
    "ODOM",
    "RIGHT_SOLE",
    "TORSO",
    "TransformBuffer",
    "TransformError",
    "require_frame",
]

ALL: builtins.list[builtins.str]
BASE_FOOTPRINT: builtins.str
BASE_LINK: builtins.str
FIELD: builtins.str
GAZE: builtins.str
LEFT_CAMERA_LINK: builtins.str
LEFT_CAMERA_OPTICAL_FRAME: builtins.str
LEFT_SOLE: builtins.str
ODOM: builtins.str
RIGHT_SOLE: builtins.str
TORSO: builtins.str

@typing.final
class FilterFailureReason:
    r"""
    Why a message was discarded before its transform became available.
    """

    EMPTY_FRAME_ID: FilterFailureReason = ...
    INVALID_FRAME_ID: FilterFailureReason = ...
    QUEUE_FULL: FilterFailureReason = ...
    def __repr__(self) -> builtins.str: ...
    def __str__(self) -> builtins.str: ...
    def __eq__(self, other: FilterFailureReason) -> builtins.bool: ...

class FrameError(builtins.Exception): ...

@typing.final
class MessageFilter:
    r"""
    Queues stamped Python messages until whirl-tf can transform them.
    """
    @property
    def pending_count(self) -> builtins.int: ...
    @property
    def queue_size(self) -> builtins.int: ...
    @property
    def tolerance_ns(self) -> builtins.int: ...
    @property
    def target_frames(self) -> builtins.list[builtins.str]: ...
    def __new__(
        cls,
        buffer: TransformBuffer,
        target_frame: builtins.str,
        queue_size: builtins.int,
        callback: typing.Optional[typing.Any] = None,
        tolerance_ns: builtins.int = ...,
    ) -> MessageFilter: ...
    def add(self, message: typing.Any) -> None: ...
    def register_callback(self, callback: typing.Any) -> None: ...
    def register_failure_callback(self, callback: typing.Any) -> None: ...
    def set_target_frame(self, target_frame: builtins.str) -> None: ...
    def set_target_frames(
        self, target_frames: typing.Sequence[builtins.str]
    ) -> None: ...
    def set_tolerance_ns(self, tolerance_ns: builtins.int) -> None: ...
    def set_queue_size(self, queue_size: builtins.int) -> None: ...
    def clear(self) -> None: ...
    def dispatch(self) -> None: ...

@typing.final
class TransformBuffer:
    def __new__(cls, history_seconds: builtins.float) -> TransformBuffer: ...
    def insert_transform(
        self,
        parent: builtins.str,
        child: builtins.str,
        matrix: typing.Sequence[typing.Sequence[builtins.float]],
        stamp_ns: builtins.int,
        is_static: builtins.bool = ...,
    ) -> None: ...
    def insert_transform_stamped(
        self, message: typing.Any, is_static: builtins.bool = ...
    ) -> None: ...
    def insert_transform_message(
        self, message: typing.Any, is_static: builtins.bool = ...
    ) -> None: ...
    def lookup(
        self, from_frame: builtins.str, to_frame: builtins.str, stamp_ns: builtins.int
    ) -> builtins.list[builtins.list[builtins.float]]: ...
    def can_transform(
        self, from_frame: builtins.str, to_frame: builtins.str, stamp_ns: builtins.int
    ) -> builtins.bool: ...
    def clear_dynamic(self) -> None: ...

class TransformError(builtins.Exception): ...

def require_frame(
    actual: builtins.str, expected: builtins.str, interface: builtins.str
) -> None: ...
