[package]
name = "whirl_tf"
description = "Timestamped coordinate-frame transforms for robotics"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true

[features]
default = ["ros"]
ros = []

[dependencies]
nalgebra.workspace = true
thiserror.workspace = true
transforms.workspace = true

[lints]
workspace = true
